### ISSUE TITLE
Broken multi module support

### ISSUE THREAD

**Issue by icetan** [icetan/mavenix#32]
See @ttuegel's comment: https://github.com/icetan/mavenix/commit/0a3c91fb4c2439d6506c6cc8ad3617ce92f3c9da#commitcomment-35596250

**Comment by ttuegel** [comment]
> Any suggestions on how to fix both issues? Run both `package` and `install`?

If `mvnix-update` runs `mvn install` at all, it will miss the intra-project dependencies.

But if we only run `mvn package` we are still only downloading the dependencies from a remote repository! Maven won't actually use the built JAR because it's part of the reactor instead of downloaded into the local repository.

Supposedly, using `mvn compile` during `buildPhase` will cause Maven to do a reactor build, but I tried that and it doesn't work. Maybe the project's POMs are wrong? But I doubt it.

**Comment by ttuegel** [comment]
Update: I think this _may_ actually be a problem with the way the project does (or doesn't) declare intra-project test dependencies, but I have to investigate more.

**Comment by ttuegel** [comment]
Most of the intra-project dependencies are detected correctly, but Maven has trouble with associated test JARs: the test JAR is normally built during the `package` phase, but when there is a dependency in another module, it needs to be built earlier, during the `compile` phase. However, this particular test JAR has dependencies on artifacts that cannot be built so early.

The recommended way to deal with associated JARs is to use `mvn install` instead of `mvn package` (during `buildPhase`) so that the associated JARs can be resolved from the local repository. That requires in turn that the local repository be writable, so it couldn't be built as a separate derivation anymore.
